### PR TITLE
Create trees module, mixing wrapper, and mixing base class

### PR DESCRIPTION
**Pull request by jcyannotty**
Updates include:
trees.py module -- similar to the linear module 
wrappers.py module -- initial work to create a nice interface for all mixing methods in Taweret
base.py module -- can act as a template/base class for all mixing methods. Outlines the default methods we expect a mixing method to have (i.e. the ones common amongst all methods such as train, predict, weights ect.)

### CODE REVIEW

**Comment by danOSU** [comment]
Screen Shot 2022-10-14 at 11 37 16 AM

**Comment by danOSU** [comment]
Screen Shot 2022-10-14 at 11 39 48 AM

**Comment by danOSU** [comment]
Screen Shot 2022-10-14 at 11 40 04 AM

**Comment by danOSU** [comment]
Screen Shot 2022-10-14 at 11 41 24 AM

**Comment by danOSU** [comment]
@jcyannotty I also wanted to ask why do we want to import modules in the __init__ ?  Is it so that we can do `from mix import linear` instead of doing `from Taweret.mix import linear` ? Are there other advantages you found while developing the tree method?

**Comment by jcyannotty** [comment]
> @jcyannotty I also wanted to ask why do we want to import modules in the **init** ? Is it so that we can do `from mix import linear` instead of doing `from Taweret.mix import linear` ? Are there other advantages you found while developing the tree method?

It makes for an easier import if we were to use the centralized "mixing" wrapper. That way you could import Taweret and the mixing function (defined in core.wrappers.py) is already imported. But you could equivalently import the module by "from Taweret.core.wrappers import mixing" (or something like that). But there are no other advantages for using it when developing the mixing modules likes trees.py. This idea came from looking at other packages.

**Pull request merged**
